#!/bin/bash

echo Loading Chaos-Core-1.0.0-generic-unstable...
sleep 0.5
echo Loading ChaosAgent.txt.exe.mpeg.png.exe.sh...
sleep 0.1
echo Starting ChaosAgent.txt.exe.mpeg.png.exe.sh...
sleep 1
mate-terminal -e ./boot/ChaosAgent.txt.exe.mpeg.png.exe.sh
echo Loading CryptoFree2022.png.exe...
sleep 0.1
echo Starting CryptoFree2022.png.exe...
sleep 0.1
echo Installing 230984 viruses...
sleep 1
echo E: wait nvm this is linux, ignoring...
sleep 0.3
echo Loading 'Free Minecraft 2022 no virus'...
sleep 0.2
echo Starting 'Free Minecraft 2022 no virus'...
sleep 0.3
echo Checking system compatibility...
sleep 1
echo Checking system OS...
sleep 0.1
echo Checking architecture...
sleep 0.3
echo Checking CPU...
sleep 0.2
echo Checking GPU...
sleep 0.2
echo Checking memory...
sleep 0.5
echo Checking kernel...
sleep 1
echo Checking resolution...
sleep 0.4
echo System is indeed compatible.
sleep 0.2
echo Killing systemd-oomd...
sleep 0.7
echo E: 'systemd-oomd' not found, ignoring...
sleep 0.5
echo Testing for viruses...
sleep 2
echo SUCCESS: No viruses found.
sleep 0.3
echo Making sure 'ChaosAgent.txt.exe.mpeg.png.exe.sh' is not misbehaving... 
sleep 5
echo E: 'ChaosAgent.txt.exe.mpeg.png.exe.sh' not found, probably killed itself already. Ignoring...
sleep 0.5
echo Initiating Physical Appearance...
sleep 0.5
echo '&speed'
sleep 1
echo '&sphere'
sleep 1.5
echo Physical Appearance initiated. Rendering...
sleep 5
echo Physical Appearance rendered. Generating Anime Girls™...
sleep 7
echo E: Anime Girls™ too hot for computer to handle, scaling back hotness factor...
sleep 14
echo SUCCESS: Anime Girls™ succesfully generated.

sleep 2
echo Chaos-Core-1.0.0-generic-unstable succesfully loaded. Launching...
xviewer ./boot/'Chaos Core-Physical Appearance.gif'
echo Chaos-Core-1.0.0-generic-unstable closed, exiting...
sleep 0.1
